# configs/config.yaml
gcp:
  project_id: "your-gcp-project-id"
  bucket_name: "your-audio-bucket"
  firestore_collection: "transcriptions"

api_keys:
  google_speech_to_text: "YOUR_GOOGLE_SPEECH_API_KEY"
